"""create customers and accounts tables

Revision ID: 13b17e0e5277
Revises: 3a49a333a279
Create Date: 2026-02-17 10:42:15.003878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13b17e0e5277'
down_revision: Union[str, Sequence[str], None] = '3a49a333a279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('kyc_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='kyc_status_enum', create_constraint=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('ledger_account_id', sa.Integer(), nullable=False),
    sa.Column('account_type', sa.Enum('CHECKING', 'SAVINGS', 'CREDIT', 'PREPAID', name='customer_account_type_enum', create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'FROZEN', 'BLOCKED', 'CLOSED', name='account_status_enum', create_constraint=True), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['ledger_account_id'], ['ledger_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_accounts_customer_id'), 'accounts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_accounts_ledger_account_id'), 'accounts', ['ledger_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_ledger_account_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_customer_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_table('customers')
    # ### end Alembic commands ###
